// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_B5uhS3qeOsRR69O83brWT9wlTP7ZVoM',
    appId: '1:753523993655:web:86b3e849c0be4bcf8e63b2',
    messagingSenderId: '753523993655',
    projectId: 'pendencias-app-26',
    authDomain: 'pendencias-app-26.firebaseapp.com',
    storageBucket: 'pendencias-app-26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALClXbg_mXOrHIkVhrJt3tvM0vTtQbFpw',
    appId: '1:753523993655:android:14c5cd63141b7f288e63b2',
    messagingSenderId: '753523993655',
    projectId: 'pendencias-app-26',
    storageBucket: 'pendencias-app-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdM1uA6P33SOtl31tWJg5qHlPXL36v2tQ',
    appId: '1:753523993655:ios:f7c8dcc0a7cc9e2c8e63b2',
    messagingSenderId: '753523993655',
    projectId: 'pendencias-app-26',
    storageBucket: 'pendencias-app-26.firebasestorage.app',
    iosBundleId: 'com.example.pendencias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdM1uA6P33SOtl31tWJg5qHlPXL36v2tQ',
    appId: '1:753523993655:ios:f7c8dcc0a7cc9e2c8e63b2',
    messagingSenderId: '753523993655',
    projectId: 'pendencias-app-26',
    storageBucket: 'pendencias-app-26.firebasestorage.app',
    iosBundleId: 'com.example.pendencias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_B5uhS3qeOsRR69O83brWT9wlTP7ZVoM',
    appId: '1:753523993655:web:a96e8a3c72e27b2c8e63b2',
    messagingSenderId: '753523993655',
    projectId: 'pendencias-app-26',
    authDomain: 'pendencias-app-26.firebaseapp.com',
    storageBucket: 'pendencias-app-26.firebasestorage.app',
  );
}
